import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/auth";
import { db } from "@/lib/db";
import { checkPermissions } from "@/lib/permissions";
import { format } from "date-fns";

export async function POST(request: NextRequest) {
  try {
    const session = await auth();
    if (!session?.user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const user = await db.user.findUnique({
      where: { id: session.user.id! },
    });

    if (!user) {
      return NextResponse.json({ error: "User not found" }, { status: 404 });
    }

    // Check if user has permission to export activities
    const canExport = await checkPermissions(user.id, "EXPORT_ACTIVITIES");
    if (!canExport && !["ADMIN", "GATEKEEPER"].includes(user.role)) {
      return NextResponse.json(
        { error: "Insufficient permissions" },
        { status: 403 }
      );
    }

    const body = await request.json();
    const { format: exportFormat, activities, stats, filters } = body;

    if (exportFormat === "pdf") {
      return await generateTextReport(activities, stats, filters, "pdf");
    } else if (exportFormat === "pptx") {
      return await generatePowerPointReport(activities, stats, filters);
    } else {
      return NextResponse.json({ error: "Invalid format" }, { status: 400 });
    }
  } catch (error) {
    console.error("Export error:", error);
    return NextResponse.json(
      { error: "Failed to export activities" },
      { status: 500 }
    );
  }
}

async function generateTextReport(
  activities: any[],
  stats: any[],
  filters: any,
  type: string
) {
  const content = {
    title: "Activity Report",
    generatedAt: format(new Date(), "PPP 'at' p"),
    totalActivities: activities.length,
    filters: {
      searchTerm: filters.searchTerm || "None",
      actionFilter:
        filters.actionFilter !== "all" ? filters.actionFilter : "All",
      userFilter: filters.userFilter !== "all" ? filters.userFilter : "All",
      dateFilter:
        filters.dateFilter !== "all" ? filters.dateFilter : "All Time",
    },
    statistics: stats.map((stat: any) => ({
      action: stat.action.replace(/_/g, " "),
      count: stat._count,
    })),
    activities: activities.slice(0, 50).map((activity: any, index: number) => ({
      index: index + 1,
      action: activity.action.replace(/_/g, " "),
      details: activity.details || "No details available",
      user: `${activity.user.name || "Unknown User"} (${activity.user.role})`,
      project: activity.project
        ? `${activity.project.name} (${activity.project.projectId})`
        : "N/A",
      date: format(new Date(activity.createdAt), "MMM dd, yyyy HH:mm"),
    })),
    hasMore: activities.length > 50,
    remainingCount: activities.length > 50 ? activities.length - 50 : 0,
  };

  const reportText = `
ACTIVITY REPORT
===============

Generated: ${content.generatedAt}
Total Activities: ${content.totalActivities}

FILTERS APPLIED
---------------
Search: ${content.filters.searchTerm}
Action: ${content.filters.actionFilter}
User: ${content.filters.userFilter}
Date: ${content.filters.dateFilter}

ACTIVITY STATISTICS
-------------------
${content.statistics.map((stat) => `${stat.action}: ${stat.count}`).join("\n")}

ACTIVITY DETAILS
----------------
${content.activities
  .map(
    (activity) =>
      `${activity.index}. ${activity.action} - ${activity.date}
   User: ${activity.user}
   Details: ${activity.details}
   Project: ${activity.project}
`
  )
  .join("\n")}

${content.hasMore ? `... and ${content.remainingCount} more activities` : ""}

Report generated by Stage Gate Management System
  `;

  return new NextResponse(reportText, {
    headers: {
      "Content-Type": "text/plain",
      "Content-Disposition": `attachment; filename="activity-report-${format(
        new Date(),
        "yyyy-MM-dd"
      )}.txt"`,
    },
  });
}

async function generatePowerPointReport(
  activities: any[],
  stats: any[],
  filters: any
) {
  const content = {
    slides: [
      {
        title: "Activity Report",
        content: [
          `Generated: ${format(new Date(), "PPP 'at' p")}`,
          `Total Activities: ${activities.length}`,
          `Report Period: ${filters.dateFilter === "all" ? "All Time" : filters.dateFilter}`,
        ],
      },
      {
        title: "Activity Overview",
        content: [
          "Key Metrics:",
          `• Total Activities: ${activities.length}`,
          `• Unique Users: ${new Set(activities.map((a: any) => a.user.id)).size}`,
          `• Projects Involved: ${new Set(activities.filter((a: any) => a.project).map((a: any) => a.project.id)).size}`,
          `• Most Recent: ${activities.length > 0 ? format(new Date(activities[0].createdAt), "MMM dd, yyyy") : "No activities"}`,
        ],
      },
      {
        title: "Activity Statistics",
        content: [
          "Activity Types:",
          ...stats.map(
            (stat: any) => `• ${stat.action.replace(/_/g, " ")}: ${stat._count}`
          ),
        ],
      },
      {
        title: "Recent Activities",
        content: [
          "Latest 10 Activities:",
          ...activities
            .slice(0, 10)
            .map(
              (activity: any, index: number) =>
                `${index + 1}. ${activity.action.replace(/_/g, " ")} by ${activity.user.name} - ${format(new Date(activity.createdAt), "MMM dd")}`
            ),
        ],
      },
      {
        title: "User Activity Summary",
        content: [
          "Top Active Users:",
          ...Object.entries(
            activities.reduce((acc: any, activity: any) => {
              acc[activity.user.name] = (acc[activity.user.name] || 0) + 1;
              return acc;
            }, {})
          )
            .sort(([, a]: any, [, b]: any) => b - a)
            .slice(0, 10)
            .map(([name, count]: any) => `• ${name}: ${count} activities`),
        ],
      },
    ],
  };

  const pptxContent = JSON.stringify(content, null, 2);

  return new NextResponse(pptxContent, {
    headers: {
      "Content-Type": "application/json",
      "Content-Disposition": `attachment; filename="activity-report-${format(
        new Date(),
        "yyyy-MM-dd"
      )}.json"`,
    },
  });
}
